media:
  input: imagens
  output: /imagens

content:
  - name: casos
    label: "Casos Periciais"
    type: file
    path: casos.json
    format: json
    list: true
    fields:
      - name: id
        label: "Codigo do Caso"
        type: string
      - name: title
        label: "Titulo do Caso"
        type: string
      - name: category
        label: "Categoria Tecnica"
        type: string
      - name: description
        label: "Descricao Resumida"
        type: text
      - name: system
        label: "Sistema Analisado"
        type: string
      - name: statusVal
        label: "Status do Caso"
        type: string
      - name: statusTag
        label: "Etiqueta de Status"
        type: string
      - name: statusColor
        label: "Cor do Status"
        type: string
      - name: visibility
        label: "Visibilidade"
        type: string
      - name: visColor
        label: "Cor da Visibilidade"
        type: string
      - name: img
        label: "Imagem de Capa"
        type: string
      - name: metodologia
        label: "Metodologia Aplicada"
        type: rich-text
      - name: resultado
        label: "Resultado Pericial"
        type: rich-text

  - name: artigos
    label: "Artigos e Debates"
    type: file
    path: artigos.json
    format: json
    list: true
    fields:
      - name: id
        label: "Identificador"
        type: string
      - name: title
        label: "Titulo do Artigo"
        type: string
      - name: category
        label: "Categoria"
        type: string
      - name: readTime
        label: "Tempo de Leitura"
        type: string
      - name: img
        label: "Imagem de Capa"
        type: string
      - name: description
        label: "Descricao Resumida"
        type: text
      - name: content
        label: "Conteudo do Artigo"
        type: rich-text
