media:
  input: imagens
  output: /imagens

content:
  - name: casos
    label: Investigações / Casos
    type: file
    path: casos.json
    format: json
    list: true
    fields:
      - name: id
        label: Código do Caso
        type: string
      - name: title
        label: Título do Caso
        type: string
      - name: category
        label: Categoria Técnica
        type: string
      - name: description
        label: Descrição Resumida
        type: text
      - name: system
        label: Sistema Analisado
        type: string
      - name: statusVal
        label: Status do Caso (Ex: Resolvido, Em Análise)
        type: string
      - name: statusTag
        label: Etiqueta de Status (Ex: Resolvido, Em Andamento)
        type: string
      - name: statusColor
        label: Cor do Status (green, yellow, red)
        type: string
      - name: visibility
        label: Visibilidade (PÚBLICO, RESTRITO)
        type: string
      - name: visColor
        label: Cor da Visibilidade (cyan, red)
        type: string
      - name: img
        label: Imagem de Capa
        type: string
      - name: metodologia
        label: Metodologia Aplicada
        type: rich-text
      - name: resultado
        label: Resultado Pericial
        type: rich-text

  - name: artigos
    label: Artigos e Debates
    type: file
    path: artigos.json
    format: json
    list: true
    fields:
      - name: id
        label: Identificador (Ex: L0G_2024.11.20)
        type: string
      - name: title
        label: Título do Artigo
        type: string
      - name: category
        label: Categoria
        type: string
      - name: readTime
        label: Tempo de Leitura (Ex: 8 min de leitura)
        type: string
      - name: img
        label: Imagem de Capa
        type: string
      - name: description
        label: Descrição Resumida
        type: text
      - name: content
        label: Conteúdo do Artigo
        type: rich-text
